### ISSUE TITLE
Installation instruction

### ISSUE THREAD

**Issue by BlackScreen** [christianbur/docker_projects#1]
Hello there,
I found your script, which seems very helpful for me - as I am using a mailcow myself.
Can you provide a little installation instruction, so that I can use it too?
Thank you very much!

**Comment by BlackScreen** [comment]
I have gotten it to work on my mailcow installation. Thank you very much for this!

**Comment by christianbur** [comment]
Glad to hear it :-)
If you have any questions, please contact me, last week I was out of town.
