### ISSUE TITLE
Max. message size

### ISSUE THREAD

**Issue by Phil12n** [christianbur/docker_projects#10]
Hi,

Is there a size limitation in getmail ? : i received today a mail with attachements (av 32Mo) in my FAI mailbox and it seems this mail blocked all the getmail process. No download for the following mails.

I tried message_size_limit = 3932160 in "/opt/mailcow-dockerized/data/conf/postfix/extra.cf" but it changes nothing.

So is there a max message size setting for getmail ? or anything else to do ?

Thanks,
Phil

**Comment by christianbur** [comment]
There is no size limitation in getmail. Maybe the email is coded incorrectly and therefore cannot be retrieved.
I had something like that in the past, then I had to transfer the email manually (with an email program). 
I would say getmail can retrieve 99.99% of emails, I just don't have the test cases for the remaining 0.01%.

**Comment by Phil12n** [comment]
Hi,
From my last post, i tried to transfer my large message from my FAI mailbox to mailcow with Outlook (drag and drop).
Outlook do not accept the mail by this way: "Unable to copy items. The size of the file you are copying is greater than the maximum size allowed by the server."
Do you know where i could increase this setting ? (cf. last post message_size_limit changes nothing)
From my pov i think this setting causes my getmail issue.
Thanks for your help,
Phil

**Comment by christianbur** [comment]
because getmail transfers the email via LMTP to dovecot-mailcow, Postix is not involved in the transfer, so the settings in the postifx config have no effect. Maybe your mailbox is full (quota).

**Comment by Phil12n** [comment]
My mailbox isn't full. This isn't a quota restriction.
I tried t send a smilar mail to another domain on the same mailcow server (but without getmail) and i've got the same issue.
So it isn't a getmail problem.
Unfortunately i'm not a specialist and i don't know where looking for ?

**Comment by Phil12n** [comment]
I founded message_size_limit, unfortunately i can't modify it !

debian@vps-xxxxxxxx:/opt/mailcow-dockerized$ sudo docker-compose exec postfix-mailcow postconf -d|grep message_size_limit
message_size_limit = 10240000
debian@vps-xxxxxxxx:/opt/mailcow-dockerized$ sudo docker-compose exec postfix-mailcow postconf -e message_size_limit=40960000
debian@vps-xxxxxxxx:/opt/mailcow-dockerized$ sudo docker-compose exec postfix-mailcow postconf -d|grep message_size_limit
message_size_limit = 10240000
????
Thanks

**Comment by christianbur** [comment]
https://mailcow.github.io/mailcow-dockerized-docs/manual-guides/Postfix/u_e-postfix-extra_cf/

**Comment by Phil12n** [comment]
Yes but with extra.cf it doesn't work !
;-(

**Comment by kiroubel-girma** [comment]
I think you are checking the postfix default values with the -d flag. Use -n instead to list non-default values.
```
# docker-compose exec postfix-mailcow postconf -n | grep message_size_limit 
message_size_limit = 104857600
```
Also size can depend on the email client. Do you have the same issue with webmail?
