### ISSUE TITLE
Unable to fetch mail

### ISSUE THREAD

**Issue by roelofz** [christianbur/docker_projects#11]
Hi,

I followed the discussion here (https://github.com/mailcow/mailcow-dockerized/issues/1554) and your install.txt.
I have a running mailcow server for about 5 years and need to integrate Imap fetching, was earlier using fetchmail.
I see the networks connected, but the fetch doesn't work as far as I can see.
from a cli in the container (using portainer) I am able to ping dovecot-mailcow and I am able to ping the external IMAP server.

Still this is what I get in the logs (even enabled debugging):

getmail-getmail-1  | 2022-10-16 11:17:42,014 - MainThread - INFO: use config file: ./settings.ini
getmail-getmail-1  | 2022-10-16 11:24:49,337 - MainThread - INFO: Caught signal 15
getmail-getmail-1  | 2022-10-16 11:24:49,337 - MainThread - INFO: START: shutdown all IMAP connections
getmail-getmail-1  | 2022-10-16 11:24:49,337 - MainThread - INFO: END: shutdown all IMAP connections
getmail-getmail-1  | 2022-10-16 11:25:07,087 - MainThread - INFO: use config file: ./settings.ini

Where to start troubleshooting?

Thanks for your help!

**Comment by christianbur** [comment]
Hi,
If the settings.ini file is empty something like this happens.
I suspect either the content or the location of the settings.ini is not correct.

**Comment by roelofz** [comment]
From within the container the ini file:
/app $ cat settings.ini
[DEFAULT]
imap_hostname:     imap.freedom.nl
imap_username:     sourceuser@freedom.nl
imap_password:     xxxx
imap_port:         993
imap_debug:        True
imap_move_enable:  False
imap_move_folder:  getmail
imap_sync_folder:  INBOX
imap_ssl:          True
lmtp_hostname:     dovecot-mailcow
lmtp_port:         24
lmtp_debug:        True
lmtp_recipient:    mailcow@user

I don't get it.

**Comment by roelofz** [comment]
Hi, I liked the idle possibility in your solution, but when it doesn't work and I'm not able to understand the failure, I need to look further, so I got fetchmail working, polling every 5 seconds.
If you come up with a solution for my case, still very interested, but no great need right now.
Thanks!

**Comment by christianbur** [comment]
In your ini file there is no custom mailbox, I only see the default settings?

Example:
[INBOX_test_gmx.de]
imap_hostname:     imap.gmx.net
imap_username:     test@gmx.de
imap_password:     xxx

https://github.com/christianbur/docker_projects/blob/master/getmail/INSTALL.TXT

**Comment by roelofz** [comment]
I thought the sections in brackets were just seperators, but they have a distinct function.
I have got it working now for all my accounts, looks very good.

Thanks!
