### ISSUE TITLE
Sync and deliver multiple folders for the same account into respective folders

### ISSUE THREAD

**Issue by gpz1100** [christianbur/docker_projects#14]
First off thank you for this tool, it provides a function missing from the main project.

My question is, say I want to sync Inbox, Sent, and Trash for the same account. What is the format of the .cfg file so content from each folder is delivered to the same respective folder in mailcow?

In testing, it appears everything is delivered to Inbox, regardless where it came from.

Thank you

**Comment by christianbur** [comment]
https://github.com/christianbur/docker_projects/blob/master/getmail/INSTALL.TXT

getmail is not suitable to syncronize folders 1:1 (Trash -> Trash), but rather to retrieve emails and pass them to the local email server. In which local folder the email ends up depends on the "sieve filter".

**Comment by christianbur** [comment]
So is built in, every email now contains two additional tags in the email header that you can filter on with Sieve. 

X-getmail-retrieved-from-mailbox-user: xxx@gmx.de
X-getmail-retrieved-from-mailbox-folder: INBOX
