### ISSUE TITLE
Pending email at imap target during mailcow reboot not retrieved

### ISSUE THREAD

**Issue by gpz1100** [christianbur/docker_projects#15]
Scenario. 
   * Mailcow server is rebooting
   * new mail has arrived at defined imap target

**Issue** - Due to timing, mailcow has not finished initializing while getmail is already up and running.  It polls the imap target, sees new mail and retrieves it.  Because mailcow not entirely up, delivery fails. This situation arises when your email volume is low. Otherwise all are grabbed when the next message arrives.

**Solution**. - A single line delay added to ``getmail_imap2lmtp.py``

**Add** ``time.sleep (30) `` under ``import time``

This will introduce a 30s pause at getmail start up which should allow mailcow to fully finish loading. 30s Is probably overkill, but this will ensure getmail can fully communicate with mailcow.

**Rebuild** with ``docker-compose build`` to apply the change.

**Comment by christianbur** [comment]
This is already built into the script, a simple spleep is not sufficient
The script checks if the local mail server is running before retrieval
something like that should be in the log:

Thread-xxx_gmx.de - INFO: LMTP deliver: start -- LMTP host: dovecot-mailcow:24
Thread-xxx_gmx.de - ERROR: LMTP deliver (ConnectionRefusedError): [Errno 111] Connection refused

**Comment by gpz1100** [comment]
Unfortunately I no longer have the log file from that day, but the above does look familiar.

It's a matter of timing. Getmail inits very quickly but mailcow takes longer. 

If im reading correctly,
Line 170 attempts to deliver. If successful it moves or deletes (depending on setting), but what if unsuccessful?  There's no corresponding else to line 170 to retry after some interval or condition.

The start up delay is one way to allow mailcow to init fully, or a function to check for a response on port 4190 from local host.

Executed from the server; 

```telnet localhost 4190
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
"IMPLEMENTATION" "Dovecot Pigeonhole"
"SIEVE" "fileinto reject envelope encoded-character vacation subaddress comparator-i;ascii-numeric relational regex imap4flags copy include variables body enotify environment mailbox date index ihave duplicate mime foreverypart extracttext vacation-seconds editheader imapflags notify imapsieve vnd.dovecot.imapsieve"
"NOTIFY" "mailto"
"SASL" "PLAIN LOGIN"
"STARTTLS"
"VERSION" "1.0"
"XCLIENT"
OK "Dovecot ready."
```

Specifically use that check for the string Dovecot ready in the early part of the code when starting up. If no response then wait 5s and retry. Keep retrying for upto a min (2 min?) then terminate if still no response.

Thoughts?

**Comment by christianbur** [comment]
Please test the script, I think the problem you describe does not occur.

**Comment by gpz1100** [comment]
It's an odd set of conditions that trigger the issue.

To test consider the following

1) Server rebooting
2) At the same time new mail has arrived at imap target
3) Getmail polls the imap target and retrieves new email

4) Because mailcow docker packages are still loading, getmail can't lmtp deliver

5) To get this queued message another message has to arrive at the imap target

At #4, are you saying getmail will reattempt lmpt redelivery? I didn't see any code for redeliver in the script.

I'm not familiar enough with docker, but another fix to this would be to ensure startup of getmail does not occur until mailcow has fully finished loading.

**Comment by gpz1100** [comment]
This issue has been affecting me again.  The scenario is quite edge case, but still an issue.

One of the accounts checked does not get mail often.  In fact it may get 0-1 emails a day. Server is set to shutdown nightly for backup. So if there's just one message waiting when it comes back, that message may not be received for days.

I don't think the above (in the OP) was actually getting applied because it was rebuilding based on github code, not local.  Had to change the ``context :`` to ``.`` and rebuild without using cache.

How difficult would it be to add a few retries, say 30s apart for the delivery part?
