### ISSUE TITLE
Problems with special character

### ISSUE THREAD

**Issue by omitron** [christianbur/docker_projects#6]
Hi!

I'm just trying to set up your get mail solution! Actually, I do not understand why the mallow team is not integrating it. But thank you for your work!
During configuration of the mail accounts there was a problem with "%" in the password string. I changed my password, to get around the problem. Did I miss something or are special characters not escaped?

thanx
Michael

**Comment by christianbur** [comment]
Bug fixed. 

https://stackoverflow.com/questions/14340366/configparser-and-string-with/28874886
https://github.com/christianbur/docker_projects/commit/248726eb1b04a296719207a18561ca2f152e9dd0
